REVOKE ALL   ON SCHEMA public FROM PUBLIC;
GRANT  USAGE ON SCHEMA public TO   PUBLIC;
GRANT  ALL   ON SCHEMA public TO   fwl_owner;

ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public GRANT ALL ON TABLES    TO fwl_admin_group;
ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public GRANT ALL ON SEQUENCES TO fwl_admin_group;
ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public GRANT ALL ON FUNCTIONS TO fwl_admin_group;
ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public GRANT ALL ON TYPES     TO fwl_admin_group;

ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public GRANT ALL ON TABLES    TO fwl_api_group;
ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public GRANT ALL ON SEQUENCES TO fwl_api_group;
ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public GRANT ALL ON FUNCTIONS TO fwl_api_group;
ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public GRANT ALL ON TYPES     TO fwl_api_group;

ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public GRANT  SELECT        ON TABLES    TO   fwl_readonly_group;
ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public GRANT  USAGE, SELECT ON SEQUENCES TO   fwl_readonly_group;
ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public REVOKE ALL           ON FUNCTIONS FROM fwl_readonly_group;
ALTER DEFAULT PRIVILEGES FOR ROLE fwl_owner IN SCHEMA public REVOKE ALL           ON TYPES     FROM fwl_readonly_group;
